// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPkwFiLtj3NZ2i4gTmGt2K0S38jptBY8',
    appId: '1:614338180587:web:114bacbbbffb656aced5ae',
    messagingSenderId: '614338180587',
    projectId: 'mycc-6a699',
    authDomain: 'mycc-6a699.firebaseapp.com',
    storageBucket: 'mycc-6a699.firebasestorage.app',
    measurementId: 'G-9NVVXLV2SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5AxQY8uap_uaFGiOJ7yo890VHq8zwIU4',
    appId: '1:614338180587:android:a58164bf726b0a3fced5ae',
    messagingSenderId: '614338180587',
    projectId: 'mycc-6a699',
    storageBucket: 'mycc-6a699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wIhpBzCNn5dBqcHLLH_CFsAlQOCMjGM',
    appId: '1:614338180587:ios:3cbe3078b5b3ac14ced5ae',
    messagingSenderId: '614338180587',
    projectId: 'mycc-6a699',
    storageBucket: 'mycc-6a699.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wIhpBzCNn5dBqcHLLH_CFsAlQOCMjGM',
    appId: '1:614338180587:ios:c05c191ca1217e6aced5ae',
    messagingSenderId: '614338180587',
    projectId: 'mycc-6a699',
    storageBucket: 'mycc-6a699.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication.RunnerTests',
  );
}
