// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXAPm91m0zh2qM18VSqHGuwMsdztmolg',
    appId: '1:162159884326:web:8f7b5e4a07cbe22eb1cee7',
    messagingSenderId: '162159884326',
    projectId: 'practice-a071a',
    authDomain: 'practice-a071a.firebaseapp.com',
    storageBucket: 'practice-a071a.appspot.com',
    measurementId: 'G-D3BJRNJVG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4R3R1biOomDhu9cr1rJVMOlGes6MMGg',
    appId: '1:162159884326:android:6e961883e3eb924fb1cee7',
    messagingSenderId: '162159884326',
    projectId: 'practice-a071a',
    storageBucket: 'practice-a071a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnDpbKlmzrjTnfr74P2xKUhnt1xJb6nM',
    appId: '1:162159884326:ios:71251dea1f1de69fb1cee7',
    messagingSenderId: '162159884326',
    projectId: 'practice-a071a',
    storageBucket: 'practice-a071a.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnDpbKlmzrjTnfr74P2xKUhnt1xJb6nM',
    appId: '1:162159884326:ios:71251dea1f1de69fb1cee7',
    messagingSenderId: '162159884326',
    projectId: 'practice-a071a',
    storageBucket: 'practice-a071a.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjXAPm91m0zh2qM18VSqHGuwMsdztmolg',
    appId: '1:162159884326:web:0607a6288bcf46f0b1cee7',
    messagingSenderId: '162159884326',
    projectId: 'practice-a071a',
    authDomain: 'practice-a071a.firebaseapp.com',
    storageBucket: 'practice-a071a.appspot.com',
    measurementId: 'G-4HB35ZQ1FL',
  );
}
